name: "Test"
env: 
  ACTIONS_ALLOW_UNSECURE_COMMANDS=true
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with: |
        echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v1
      with:
        packages: hello,docker
        script: |
          hello
          docker --help
